iPlug2: IRECT Struct Reference
IRECT Struct Reference
IGraphics::Structs
Used to manage a rectangular area, independent of draw class/platform.
#include <IGraphicsStructs.h>
Public Member Functions
IRECT ()
Construct an empty IRECT.
IRECT (float l, float t, float r, float b)
Construct a new IRECT with dimensions.
IRECT (float x, float y, const IBitmap &bitmap)
Construct a new IRECT at the given position and with the same size as the bitmap.
bool Empty () const
void Clear ()
Set all fields of this IRECT to 0.
bool operator== (const IRECT &rhs) const
bool operator!= (const IRECT &rhs) const
float W () const
float H () const
float MW () const
float MH () const
float Area () const
IRECT Union (const IRECT &rhs) const
Create a new IRECT that is a union of this IRECT and rhs.
IRECT Intersect (const IRECT &rhs) const
Create a new IRECT that is the intersection of this IRECT and rhs.
bool Intersects (const IRECT &rhs) const
Returns true if this IRECT shares any common pixels with rhs, false otherwise.
bool Contains (const IRECT &rhs) const
Returns true if this IRECT completely contains rhs.
bool Contains (float x, float y) const
Returns true if this IRECT completely contains the point (x,y).
bool ContainsEdge (float x, float y) const
Returns true if the point (x,y) is either contained in this IRECT or on an edge.
void Constrain (float &x, float &y) const
Ensure the point (x,y) is inside this IRECT.
IRECT Inset (const IRECT &rhs) const
Offsets the input IRECT based on the parent.
bool Mergeable (const IRECT &rhs) const
Return if this IRECT and rhs may be merged.
IRECT FracRect (EDirection layoutDir, float frac, bool fromTopOrRight=false) const
Get a new rectangle which is a fraction of this rectangle.
IRECT FracRectHorizontal (float frac, bool rhs=false) const
Returns a new IRECT with a width that is multiplied by frac.
IRECT FracRectVertical (float frac, bool fromTop=false) const
Returns a new IRECT with a height that is multiplied by frac.
IRECT SubRectVertical (int numSlices, int sliceIdx) const
Returns a new IRECT which is a horizontal "slice" of this IRECT.
IRECT SubRectHorizontal (int numSlices, int sliceIdx) const
Returns a new IRECT which is a vertical "slice" of this IRECT.
IRECT SubRect (EDirection layoutDir, int numSlices, int sliceIdx) const
Get a new rectangle which is a "slice" of this rectangle.
IRECT GetFromTLHC (float w, float h) const
Get a subrect of this IRECT expanding from the top-left corner.
IRECT GetFromBLHC (float w, float h) const
Get a subrect of this IRECT expanding from the bottom-left corner.
IRECT GetFromTRHC (float w, float h) const
Get a subrect of this IRECT expanding from the top-right corner.
IRECT GetFromBRHC (float w, float h) const
Get a subrect of this IRECT expanding from the bottom-right corner.
IRECT GetFromTop (float amount) const
Get a subrect of this IRECT bounded in Y by the top edge and 'amount'.
IRECT GetFromBottom (float amount) const
Get a subrect of this IRECT bounded in Y by 'amount' and the bottom edge.
IRECT GetFromLeft (float amount) const
Get a subrect of this IRECT bounded in X by the left edge and 'amount'.
IRECT GetFromRight (float amount) const
Get a subrect of this IRECT bounded in X by 'amount' and the right edge.
IRECT GetReducedFromTop (float amount) const
Get a subrect of this IRECT reduced in height from the top edge by 'amount'.
IRECT GetReducedFromBottom (float amount) const
Get a subrect of this IRECT reduced in height from the bottom edge by 'amount'.
IRECT GetReducedFromLeft (float amount) const
Get a subrect of this IRECT reduced in width from the left edge by 'amount'.
IRECT GetReducedFromRight (float amount) const
Get a subrect of this IRECT reduced in width from the right edge by 'amount'.
IRECT ReduceFromTop (float amount)
Reduce in height from the top edge by 'amount' and return the removed region.
IRECT ReduceFromBottom (float amount)
Reduce in height from the bottom edge by 'amount' and return the removed region.
IRECT ReduceFromLeft (float amount)
Reduce in width from the left edge by 'amount' and return the removed region.
IRECT ReduceFromRight (float amount)
Reduce in width from the right edge by 'amount' and return the removed region.
IRECT GetGridCell (int row, int col, int nRows, int nColumns) const
Get a subrect (by row, column) of this IRECT which is a cell in a grid of size (nRows * nColumns)
IRECT GetGridCell (int cellIndex, int nRows, int nColumns, EDirection dir=EDirection::Horizontal, int nCells=1) const
Get a subrect (by index) of this IRECT which is a cell (or union of nCells sequential cells on same row/column) in a grid of size (nRows * nColumns)
bool IsPixelAligned () const
bool IsPixelAligned (float scale) const
Return true if, when scaled by scale, this IRECT is pixel aligned When scaling this mutliples each value of the IRECT, it does not scale from the center.
void PixelAlign ()
Pixel aligns the rect in an inclusive manner (moves all points outwards)
void PixelAlign (float scale)
Pixel-align this IRECT at the given scale factor then scale it back down When scaling this mutliples each value of the IRECT, it does not scale from the center.
IRECT GetPixelAligned () const
Get a copy of this IRECT with PixelAlign() called.
IRECT GetPixelAligned (float scale) const
Get a copy of this IRECT with PixelAlign(scale) called.
void PixelSnap ()
Pixel aligns to nearest pixels This may make the IRECT smaller, unlike PixelAlign().
void PixelSnap (float scale)
Pixel align a scaled version of this IRECT.
IRECT GetPixelSnapped () const
IRECT GetPixelSnapped (float scale) const
Get a copy of this IRECT with PixelSnap(scale) called.
void Pad (float padding)
Pad this IRECT N.B.
void Pad (float padL, float padT, float padR, float padB)
Pad this IRECT N.B.
void HPad (float padding)
Pad this IRECT in the X-axis N.B.
void VPad (float padding)
Pad this IRECT in the Y-axis N.B.
void MidHPad (float padding)
Set the width of this IRECT to 2*padding without changing it's center point on the X-axis.
void MidVPad (float padding)
Set the height of this IRECT to 2*padding without changing it's center point on the Y-axis.
IRECT GetPadded (float padding) const
Get a copy of this IRECT with each value padded by padding N.B.
IRECT GetPadded (float padL, float padT, float padR, float padB) const
Get a copy of this IRECT with the values padded N.B.
IRECT GetHPadded (float padding) const
Get a copy of this IRECT padded in the X-axis N.B.
IRECT GetVPadded (float padding) const
Get a copy of this IRECT padded in the Y-axis N.B.
IRECT GetMidHPadded (float padding) const
Get a copy of this IRECT where its width = 2 * padding but the center point on the X-axis has not changed.
IRECT GetMidVPadded (float padding) const
Get a copy of this IRECT where its height = 2 * padding but the center point on the Y-axis has not changed.
IRECT GetHSliced (float w, bool rhs=false) const
Get a copy of this IRECT with a new width.
IRECT GetVSliced (float h, bool bot=false) const
Get a copy of this IRECT with a new height.
void Clank (const IRECT &rhs)
/todo
void Scale (float scale)
Multiply each field of this IRECT by scale.
void ScaleAboutCentre (float scale)
Scale the width and height of this IRECT by scale without changing the center point.
IRECT GetScaled (float scale) const
Get a copy of this IRECT with all values multiplied by scale.
IRECT GetScaledAboutCentre (float scale) const
Get a copy of this IRECT where the width and height are multiplied by scale without changing the center point.
void GetRandomPoint (float &x, float &y) const
Get a random point within this rectangle.
IRECT GetRandomSubRect () const
void Alter (float l, float t, float r, float b)
Offset each field of the rectangle.
IRECT GetAltered (float l, float t, float r, float b) const
Get a copy of this rectangle where each field is offset.
void Translate (float x, float y)
Translate this rectangle.
IRECT GetTranslated (float x, float y) const
Get a translated copy of this rectangle.
IRECT GetHShifted (float x) const
Get a copy of this rectangle translated on the X axis.
IRECT GetVShifted (float y) const
Get a copy of this rectangle translated on the Y axis.
IRECT GetCentredInside (const IRECT &sr) const
Get a rectangle the size of sr but with the same center point as this rectangle.
IRECT GetCentredInside (float w, float h=0.f) const
Get a rectangle with the same center point as this rectangle and the given size.
IRECT GetCentredInside (const IBitmap &bitmap) const
Get a rectangle with the same center point as this rectangle and the size of the bitmap.
void VAlignTo (const IRECT &sr, EVAlign align)
Vertically align this rect to the reference IRECT.
void HAlignTo (const IRECT &sr, EAlign align)
Horizontally align this rect to the reference IRECT.
IRECT GetVAlignedTo (const IRECT &sr, EVAlign align) const
Get a rectangle the same dimensions as this one, vertically aligned to the reference IRECT.
float GetLengthOfShortestSide () const
IRECT GetHAlignedTo (const IRECT &sr, EAlign align) const
Get a rectangle the same dimensions as this one, horizontally aligned to the reference IRECT.
void DBGPrint ()
Static Public Member Functions
static IRECT MakeXYWH (float l, float t, float w, float h)
Create a new IRECT with the given position and size.
static IRECT LinearInterpolateBetween (const IRECT &start, const IRECT &dest, float progress)
Get a rectangle that is a linear interpolation between start and dest
Public Attributes
float L
Left side of the rectangle (X)
float T
Top of the rectangle (Y)
float R
Right side of the rectangle (X + W)
float B
Bottom of the rectangle (Y + H)
Detailed Description
Used to manage a rectangular area, independent of draw class/platform.
An IRECT is always specified in 1:1 pixels, any scaling for high DPI happens in the drawing class. In IGraphics 0,0 is top left.
Definition at line 729 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
IRECT::IRECT (float l, float t, float r, float b) inline
Construct a new IRECT with dimensions.
Parameters
l Left
t Top
r Right
b Bottom
Definition at line 751 of file IGraphicsStructs.h.
IRECT::IRECT (float x, float y, const IBitmap & bitmap) inline
Construct a new IRECT at the given position and with the same size as the bitmap.
Parameters
x Top
y Left
bitmap Bitmap for the size
Definition at line 759 of file IGraphicsStructs.h.
References IBitmap::FH(), and IBitmap::FW().
Member Function Documentation
void IRECT::Alter (float l, float t, float r, float b) inline
Offset each field of the rectangle.
Parameters
l Left offset
t Top offset
r Right offset
b Bottom offset
Definition at line 1505 of file IGraphicsStructs.h.
Referenced by IVGroupControl::OnResize().
float IRECT::Area () const inline
Returns
float the area of this IRECT
Definition at line 813 of file IGraphicsStructs.h.
References IBitmap::H(), and IBitmap::W().
void IRECT::Clank (const IRECT & rhs) inline
/todo
Parameters
rhs /todo
Definition at line 1394 of file IGraphicsStructs.h.
References B, L, R, and T.
void IRECT::Constrain (float & x, float & y) const inline
Ensure the point (x,y) is inside this IRECT.
Parameters
x point X, will be modified if it's outside this IRECT
y point Y, will be modified if it's outside this IRECT
Definition at line 880 of file IGraphicsStructs.h.
Referenced by IVKeyboardControl::Draw(), IVXYPadControl::OnMouseDrag(), IVMultiSliderControl< MAXNC >::SnapToMouse(), and IControl::SnapToMouse().
bool IRECT::Contains (const IRECT & rhs) const inline
Returns true if this IRECT completely contains rhs.
Parameters
rhs another IRECT
Returns
true if this IRECT completely contains rhs
false if any part of rhs is outside this IRECT
Definition at line 851 of file IGraphicsStructs.h.
References B, Empty(), L, R, and T.
Referenced by IPopupMenuControl::CalculateMenuPanels(), IVKeyboardControl::Draw(), IVButtonControl::IsHit(), IVSwitchControl::IsHit(), IVKnobControl::IsHit(), IVSliderControl::IsHit(), IControl::IsHit(), IVNumberBoxControl::OnMouseDblClick(), ITextEntryControl::OnMouseDown(), TestDirBrowseControl::OnMouseDown(), IVKnobControl::OnMouseDown(), IVSliderControl::OnMouseDown(), IGraphicsLiveEdit::OnMouseDrag(), TestBezierControl::OnMouseOver(), IGraphicsLiveEdit::OnMouseOver(), IVKnobControl::OnMouseOver(), IVSliderControl::OnMouseOver(), IVRangeSliderControl::OnMouseOver(), and IGraphics::ReleaseMouseCapture().
bool IRECT::Contains (float x, float y) const inline
Returns true if this IRECT completely contains the point (x,y).
Parameters
x point X
y point Y
Returns
true the point (x,y) is inside this IRECT
false the point (x,y) is outside this IRECT
Definition at line 861 of file IGraphicsStructs.h.
bool IRECT::ContainsEdge (float x, float y) const inline
Returns true if the point (x,y) is either contained in this IRECT or on an edge.
Unlike Contains(x,y) this method includes right-most and bottom-most pixels.
Parameters
x point X
y point Y
Returns
true the point (x,y) is inside this IRECT
false the point (x,y) is outside this IRECT
Definition at line 872 of file IGraphicsStructs.h.
bool IRECT::Empty () const inline
Returns
bool true if all the fields of this IRECT are 0
Definition at line 779 of file IGraphicsStructs.h.
Referenced by IPopupMenuControl::CalculateMenuPanels(), Contains(), IGraphicsLiveEdit::Draw(), IVGroupControl::Draw(), Intersects(), Mergeable(), IGraphicsPathBase::PathClipRegion(), IBubbleControl::SetMaxBounds(), and Union().
IRECT IRECT::FracRect (EDirection layoutDir, float frac, bool fromTopOrRight = false) const inline
Get a new rectangle which is a fraction of this rectangle.
Parameters
layoutDir EDirection::Vertical or EDirection::Horizontal
frac Fractional multiplier
fromTopOrRight If true the new rectangle will expand from the top (Vertical) or right (Horizontal) otherwise it will expand from the bottom (Vertical) or left (Horizontal)
Returns
IRECT the new rectangle
Definition at line 916 of file IGraphicsStructs.h.
Referenced by IVSliderControl::Draw(), IVRangeSliderControl::Draw(), and IVTrackControlBase::SetParams().
IRECT IRECT::FracRectHorizontal (float frac, bool rhs = false) const inline
Returns a new IRECT with a width that is multiplied by frac.
Parameters
frac width multiplier
rhs if true, the new IRECT will expand/contract from the right, otherwise it will come from the left
Returns
IRECT the new IRECT
Definition at line 928 of file IGraphicsStructs.h.
References IBitmap::W().
Referenced by IVColorSwatchControl::Draw(), IRECTList::GetFracGrid(), and ICaptionControl::OnResize().
IRECT IRECT::FracRectVertical (float frac, bool fromTop = false) const inline
Returns a new IRECT with a height that is multiplied by frac.
Parameters
frac height multiplier
fromTop if true, the new IRECT will expand/contract from the top, otherwise it will come from the bottom
Returns
IRECT the new IRECT
Definition at line 942 of file IGraphicsStructs.h.
References IBitmap::H().
Referenced by IWheelControl::Draw(), IRECTList::GetFracGrid(), IVNumberBoxControl::OnAttached(), and IVNumberBoxControl::OnResize().
IRECT IRECT::GetAltered (float l, float t, float r, float b) const inline
Get a copy of this rectangle where each field is offset.
Parameters
l Left offset
t Top offset
r Right offset
b Bottom offset
Returns
IRECT the new rectangle
Definition at line 1519 of file IGraphicsStructs.h.
IRECT IRECT::GetCentredInside (const IRECT & sr) const inline
Get a rectangle the size of sr but with the same center point as this rectangle.
Parameters
sr Size rectangle
Returns
IRECT the new rectangle
Definition at line 1563 of file IGraphicsStructs.h.
References B, H(), L, R, T, and W().
Referenced by TestMaskControl::Draw(), TestDrawContextControl::Draw(), TestFontControl::Draw(), TestBezierControl::Draw(), ILEDControl::Draw(), IBSliderControl::Draw(), IPopupMenuControl::DrawCellText(), IPopupMenuControl::DrawTick(), IVKnobControl::GetKnobDragBounds(), IVRadioButtonControl::IVRadioButtonControl(), TestDirBrowseControl::OnResize(), ISVGSliderControl::OnResize(), IBSliderControl::OnResize(), and ICaptionControl::OnResize().
IRECT IRECT::GetCentredInside (float w, float h = 0.f) const inline
Get a rectangle with the same center point as this rectangle and the given size.
Parameters
w Width of the new rectangle (minimum 1.0)
h Height of the new rectangle (a value of 0 will make it the same as w, thus a square)
Returns
IRECT the new rectangle
Definition at line 1578 of file IGraphicsStructs.h.
References B, L, R, and T.
IRECT IRECT::GetCentredInside (const IBitmap & bitmap) const inline
Get a rectangle with the same center point as this rectangle and the size of the bitmap.
Parameters
bitmap Bitmap used to size the new rectangle
Returns
IRECT the new rectangle
Definition at line 1597 of file IGraphicsStructs.h.
References B, IBitmap::FH(), IBitmap::FW(), L, R, and T.
IRECT IRECT::GetFromBLHC (float w, float h) const inline
Get a subrect of this IRECT expanding from the bottom-left corner.
Parameters
w Width of the desired IRECT
h Height of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1005 of file IGraphicsStructs.h.
IRECT IRECT::GetFromBottom (float amount) const inline
Get a subrect of this IRECT bounded in Y by 'amount' and the bottom edge.
Parameters
amount Size in Y of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1027 of file IGraphicsStructs.h.
Referenced by TestFontControl::Draw(), IWheelControl::Draw(), IVectorBase::DrawPressableTriangle(), and TestDirBrowseControl::OnResize().
IRECT IRECT::GetFromBRHC (float w, float h) const inline
Get a subrect of this IRECT expanding from the bottom-right corner.
Parameters
w Width of the desired IRECT
h Height of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1017 of file IGraphicsStructs.h.
Referenced by ICornerResizerControl::OnRescale().
IRECT IRECT::GetFromLeft (float amount) const inline
Get a subrect of this IRECT bounded in X by the left edge and 'amount'.
Parameters
amount Size in X of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1032 of file IGraphicsStructs.h.
Referenced by IVRadioButtonControl::IVRadioButtonControl().
IRECT IRECT::GetFromRight (float amount) const inline
Get a subrect of this IRECT bounded in X by 'amount' and the right edge.
Parameters
amount Size in X of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1037 of file IGraphicsStructs.h.
Referenced by IVRadioButtonControl::IVRadioButtonControl(), and TestDirBrowseControl::OnResize().
IRECT IRECT::GetFromTLHC (float w, float h) const inline
Get a subrect of this IRECT expanding from the top-left corner.
Parameters
w Width of the desired IRECT
h Weight of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 999 of file IGraphicsStructs.h.
IRECT IRECT::GetFromTop (float amount) const inline
Get a subrect of this IRECT bounded in Y by the top edge and 'amount'.
Parameters
amount Size in Y of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1022 of file IGraphicsStructs.h.
Referenced by TestFontControl::Draw(), and IVectorBase::DrawPressableTriangle().
IRECT IRECT::GetFromTRHC (float w, float h) const inline
Get a subrect of this IRECT expanding from the top-right corner.
Parameters
w Width of the desired IRECT
h Height of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1011 of file IGraphicsStructs.h.
IRECT IRECT::GetGridCell (int row, int col, int nRows, int nColumns) const inline
Get a subrect (by row, column) of this IRECT which is a cell in a grid of size (nRows * nColumns)
Parameters
row Row index of the desired subrect
col Column index of the desired subrect
nRows Number of rows in the cell grid
nColumns Number of columns in the cell grid
Returns
IRECT The resulting subrect
Definition at line 1085 of file IGraphicsStructs.h.
References SubRectHorizontal().
Referenced by TestBlendControl::Draw(), IVLEDMeterControl< MAXNC >::Draw(), and IVColorSwatchControl::OnResize().
IRECT IRECT::GetGridCell (int cellIndex, int nRows, int nColumns, EDirection dir = EDirection::Horizontal, int nCells = 1) const inline
Get a subrect (by index) of this IRECT which is a cell (or union of nCells sequential cells on same row/column) in a grid of size (nRows * nColumns)
Parameters
cellIndex Index of the desired cell in the cell grid
nRows Number of rows in the cell grid
nColumns Number of columns in the cell grid
dir Desired direction of indexing, by row (EDirection::Horizontal) or by column (EDirection::Vertical)
nCells Number of desired sequential cells to join (on same row/column)
Returns
IRECT The resulting subrect
Definition at line 1100 of file IGraphicsStructs.h.
References SubRectHorizontal(), SubRectVertical(), and Union().
IRECT IRECT::GetHAlignedTo (const IRECT & sr, EAlign align) const inline
Get a rectangle the same dimensions as this one, horizontally aligned to the reference IRECT.
Parameters
sr the IRECT to use as reference
align the horizontal alignment
Returns
the new rectangle
Definition at line 1660 of file IGraphicsStructs.h.
References IBitmap::H(), HAlignTo(), and IBitmap::W().
IRECT IRECT::GetHPadded (float padding) const inline
Get a copy of this IRECT padded in the X-axis N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Left and right padding
Returns
IRECT the new rectangle
Definition at line 1338 of file IGraphicsStructs.h.
Referenced by IVSliderControl::Draw(), and IPopupMenuControl::DrawCellBackground().
IRECT IRECT::GetHShifted (float x) const inline
Get a copy of this rectangle translated on the X axis.
Parameters
x Offset
Returns
IRECT the new rectangle
Definition at line 1547 of file IGraphicsStructs.h.
IRECT IRECT::GetHSliced (float w, bool rhs = false) const inline
Get a copy of this IRECT with a new width.
Parameters
w Width of the new rectangle
rhs If true the new rectangle will expand from the right side, otherwise it will expand from the left
Returns
IRECT the new rectangle
Definition at line 1372 of file IGraphicsStructs.h.
float IRECT::GetLengthOfShortestSide () const inline
Returns
float Either the width or the height of the rectangle, whichever is less
Definition at line 1648 of file IGraphicsStructs.h.
References IBitmap::H(), and IBitmap::W().
IRECT IRECT::GetMidHPadded (float padding) const inline
Get a copy of this IRECT where its width = 2 * padding but the center point on the X-axis has not changed.
Parameters
padding Left and right padding (1/2 the new width)
Returns
IRECT the new rectangle
Definition at line 1355 of file IGraphicsStructs.h.
Referenced by IVRangeSliderControl::Draw(), IVSliderControl::OnResize(), and IBSliderControl::OnResize().
IRECT IRECT::GetMidVPadded (float padding) const inline
Get a copy of this IRECT where its height = 2 * padding but the center point on the Y-axis has not changed.
Parameters
padding Top and bottom padding (1/2 the new height)
Returns
IRECT the new rectangle
Definition at line 1363 of file IGraphicsStructs.h.
Referenced by IVRangeSliderControl::Draw(), IWheelControl::Draw(), IVectorBase::DrawPressableTriangle(), IVSliderControl::OnResize(), and IBSliderControl::OnResize().
IRECT IRECT::GetPadded (float padding) const inline
Get a copy of this IRECT with each value padded by padding N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Padding amount
Returns
IRECT the new rectangle
Definition at line 1317 of file IGraphicsStructs.h.
Referenced by IGraphics::BeginFrame(), IPopupMenuControl::CalculateMenuPanels(), IGraphicsLice::DoDrawText(), TestLayerControl::Draw(), TestPolyControl::Draw(), TestMultiPathControl::Draw(), TestGradientControl::Draw(), TestArcControl::Draw(), TestBlendControl::Draw(), TestDirBrowseControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::Draw(), IFPSDisplayControl::Draw(), IBubbleControl::Draw(), IVLEDMeterControl< MAXNC >::Draw(), IVKeyboardControl::Draw(), IVRangeSliderControl::Draw(), IVXYPadControl::Draw(), IVGroupControl::Draw(), IVColorSwatchControl::Draw(), IWheelControl::Draw(), IPopupMenuControl::DrawPanelShadow(), IVectorBase::DrawPressableRectangle(), IGraphics::IsDirty(), IVBakedPresetManagerControl::OnAttached(), IVDiskPresetManagerControl::OnAttached(), TestDirBrowseControl::OnResize(), IVDisplayControl::OnResize(), IVSliderControl::OnResize(), IVGroupControl::OnResize(), IVColorSwatchControl::OnResize(), and ISVGSliderControl::OnResize().
IRECT IRECT::GetPadded (float padL, float padT, float padR, float padB) const inline
Get a copy of this IRECT with the values padded N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padL Left-padding
padT Top-padding
padR Right-padding
padB Bottom-padding
Returns
IRECT the new rectangle
Definition at line 1329 of file IGraphicsStructs.h.
IRECT IRECT::GetPixelAligned () const inline
Get a copy of this IRECT with PixelAlign() called.
Returns
IRECT the new rectangle
Definition at line 1197 of file IGraphicsStructs.h.
References PixelAlign().
Referenced by IGraphics::BeginFrame(), IGraphicsLice::DoDrawText(), and IGraphics::StartLayer().
IRECT IRECT::GetPixelAligned (float scale) const inline
Get a copy of this IRECT with PixelAlign(scale) called.
Parameters
scale Scaling factor for the alignment
Returns
IRECT the new rectangle
Definition at line 1207 of file IGraphicsStructs.h.
References PixelAlign().
IRECT IRECT::GetPixelSnapped () const inline
Returns
IRECT A copy of this IRECT with PixelSnap() called
Definition at line 1235 of file IGraphicsStructs.h.
References PixelSnap().
Referenced by IGraphics::GetPixelSnapped().
IRECT IRECT::GetPixelSnapped (float scale) const inline
Get a copy of this IRECT with PixelSnap(scale) called.
Parameters
Scaling factor for the alignment
Returns
IRECT the new rectangle
Definition at line 1245 of file IGraphicsStructs.h.
References PixelSnap().
void IRECT::GetRandomPoint (float & x, float & y) const inline
Get a random point within this rectangle.
Parameters
x OUT output X value of point
y OUT output Y value of point
Definition at line 1480 of file IGraphicsStructs.h.
References IBitmap::H(), and IBitmap::W().
Referenced by GetRandomSubRect().
IRECT IRECT::GetRandomSubRect () const inline
Returns
IRECT A random rectangle inside this IRECT
Definition at line 1490 of file IGraphicsStructs.h.
References GetRandomPoint().
Referenced by TestAnimationControl::OnMouseDown().
IRECT IRECT::GetReducedFromBottom (float amount) const inline
Get a subrect of this IRECT reduced in height from the bottom edge by 'amount'.
Parameters
amount Size in Y to reduce by
Returns
IRECT The resulting subrect
Definition at line 1047 of file IGraphicsStructs.h.
Referenced by IVectorBase::DrawPressableTriangle().
IRECT IRECT::GetReducedFromLeft (float amount) const inline
Get a subrect of this IRECT reduced in width from the left edge by 'amount'.
Parameters
amount Size in X to reduce by
Returns
IRECT The resulting subrect
Definition at line 1052 of file IGraphicsStructs.h.
IRECT IRECT::GetReducedFromRight (float amount) const inline
Get a subrect of this IRECT reduced in width from the right edge by 'amount'.
Parameters
amount Size in X to reduce by
Returns
IRECT The resulting subrect
Definition at line 1057 of file IGraphicsStructs.h.
IRECT IRECT::GetReducedFromTop (float amount) const inline
Get a subrect of this IRECT reduced in height from the top edge by 'amount'.
Parameters
amount Size in Y to reduce by
Returns
IRECT The resulting subrect
Definition at line 1042 of file IGraphicsStructs.h.
Referenced by IVectorBase::DrawPressableTriangle().
IRECT IRECT::GetScaled (float scale) const inline
Get a copy of this IRECT with all values multiplied by scale.
Parameters
scale The amount to multiply each value by
Returns
IRECT the resulting rectangle
Definition at line 1445 of file IGraphicsStructs.h.
References Scale().
Referenced by IGraphicsAGG::DrawBitmap().
IRECT IRECT::GetScaledAboutCentre (float scale) const inline
Get a copy of this IRECT where the width and height are multiplied by scale without changing the center point.
Parameters
scale Scaling factor
Returns
IRECT the resulting rectangle
Definition at line 1455 of file IGraphicsStructs.h.
References ScaleAboutCentre().
Referenced by ILEDControl::Draw(), and IVectorBase::DrawPressableTriangle().
IRECT IRECT::GetTranslated (float x, float y) const inline
Get a translated copy of this rectangle.
Parameters
x Offset in the X axis
y Offset in the Y axis
Returns
IRECT the new rectangle
Definition at line 1539 of file IGraphicsStructs.h.
Referenced by IVLabelControl::Draw(), IWheelControl::Draw(), PlaceHolder::Draw(), IVectorBase::DrawPressableRectangle(), IVectorBase::DrawPressableTriangle(), and IRECTList::GetFracGrid().
IRECT IRECT::GetVAlignedTo (const IRECT & sr, EVAlign align) const inline
Get a rectangle the same dimensions as this one, vertically aligned to the reference IRECT.
Parameters
sr the source IRECT to use as reference
align the vertical alignment
Returns
the new rectangle
Definition at line 1640 of file IGraphicsStructs.h.
References VAlignTo().
IRECT IRECT::GetVPadded (float padding) const inline
Get a copy of this IRECT padded in the Y-axis N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Top and bottom padding
Returns
IRECT the new rectangle
Definition at line 1347 of file IGraphicsStructs.h.
Referenced by ITextEntryControl::Draw(), IVSliderControl::Draw(), IVPlotControl::Draw(), and IVGroupControl::OnResize().
IRECT IRECT::GetVShifted (float y) const inline
Get a copy of this rectangle translated on the Y axis.
Parameters
y Offset
Returns
IRECT the new rectangle
Definition at line 1555 of file IGraphicsStructs.h.
IRECT IRECT::GetVSliced (float h, bool bot = false) const inline
Get a copy of this IRECT with a new height.
Parameters
h Height of the new rectangle
bot If true the new rectangle will expand from the bottom, otherwise it will expand from the top
Returns
IRECT the new rectangle
Definition at line 1384 of file IGraphicsStructs.h.
float IRECT::H () const inline
Returns
float the height of this IRECT
Definition at line 804 of file IGraphicsStructs.h.
Referenced by IGraphics::BeginFrame(), IPopupMenuControl::CreatePopupMenu(), IGraphicsCanvas::DoDrawText(), IGraphicsLice::DoDrawText(), TestDrawContextControl::Draw(), TestLayerControl::Draw(), TestShadowGradientControl::Draw(), TestGradientControl::Draw(), TestMultiPathControl::Draw(), IColorPickerControl::Draw(), ISkLottieControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::Draw(), IVDisplayControl::Draw(), IFPSDisplayControl::Draw(), IVLEDMeterControl< MAXNC >::Draw(), IVKeyboardControl::Draw(), ISkShaderControl::Draw(), IVXYPadControl::Draw(), IVPlotControl::Draw(), ISVGKnobControl::Draw(), IWheelControl::Draw(), ITextControl::Draw(), IURLControl::Draw(), IGraphicsCanvas::DrawBitmap(), IGraphicsLice::DrawBitmap(), IGraphicsCairo::DrawBitmap(), IGraphicsNanoVG::DrawBitmap(), IGraphics::DrawBitmapedText(), IGraphicsPathBase::DrawData(), IGraphicsNanoVG::DrawDottedRect(), IGraphicsLice::DrawFittedBitmap(), IGraphicsPathBase::DrawFittedBitmap(), IGraphics::DrawFittedLayer(), IGraphics::DrawGrid(), IPopupMenuControl::DrawPanelShadow(), IVectorBase::DrawPressableTriangle(), IGraphicsLice::DrawRoundRect(), IGraphicsPathBase::DrawSVG(), IGraphicsLice::FillRect(), IGraphicsLice::FillRoundRect(), GetCentredInside(), IRECTList::GetFracGrid(), IVKnobControl::GetKnobDragBounds(), IFlexBox::Init(), IGraphicsCairo::LoadAPIFont(), IGraphicsNanoVG::LoadAPIFont(), IWebViewControl::OnAttached(), ITextEntryControl::OnKeyDown(), ICornerResizerControl::OnMouseDblClick(), IShaderControl::OnMouseDown(), IVMultiSliderControl< MAXNC >::OnMouseDown(), IShaderControl::OnMouseDrag(), IGraphicsLiveEdit::OnMouseDrag(), IVXYPadControl::OnMouseDrag(), IShaderControl::OnMouseUp(), IWebViewControl::OnRescale(), TestSizeControl::OnResize(), IWebViewControl::OnResize(), IShaderControl::OnResize(), IVGroupControl::OnResize(), ISVGSliderControl::OnResize(), PlaceHolder::OnResize(), IGraphicsPathBase::PathEllipse(), IGraphicsPathBase::PathRoundRect(), IBubbleControl::SetMaxBounds(), IVTrackControlBase::SetParams(), IControl::SetPosition(), IVMultiSliderControl< MAXNC >::SnapToMouse(), IControl::SnapToMouse(), IGraphics::StartLayer(), IMatrix::Transform(), and VAlignTo().
void IRECT::HAlignTo (const IRECT & sr, EAlign align) inline
Horizontally align this rect to the reference IRECT.
Parameters
sr the IRECT to use as reference
align the horizontal alignment
Definition at line 1625 of file IGraphicsStructs.h.
References L, R, IBitmap::W(), and W().
Referenced by GetHAlignedTo().
void IRECT::HPad (float padding) inline
Pad this IRECT in the X-axis N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Left and right padding
Definition at line 1280 of file IGraphicsStructs.h.
Referenced by IPopupMenuControl::CreatePopupMenu(), IVGroupControl::OnResize(), and IBubbleControl::SetMaxBounds().
IRECT IRECT::Inset (const IRECT & rhs) const inline
Offsets the input IRECT based on the parent.
Parameters
rhs IRECT to offset
Definition at line 891 of file IGraphicsStructs.h.
References B, L, R, and T.
Referenced by TestFlexBoxControl::OnResize().
IRECT IRECT::Intersect (const IRECT & rhs) const inline
Create a new IRECT that is the intersection of this IRECT and rhs.
The resulting IRECT will have the maximum L and T values and minimum R and B values of the inputs.
Parameters
rhs another IRECT
Returns
IRECT the new IRECT
Definition at line 830 of file IGraphicsStructs.h.
References B, L, R, and T.
Referenced by IGraphics::BeginFrame(), IGraphicsLice::DrawBitmap(), IGraphicsAGG::DrawBitmap(), IGraphicsLice::FillRect(), IRECTList::GetFracGrid(), IRECTList::Optimize(), and IGraphicsPathBase::PathClipRegion().
bool IRECT::Intersects (const IRECT & rhs) const inline
Returns true if this IRECT shares any common pixels with rhs, false otherwise.
Parameters
rhs another IRECT
Returns
true this IRECT shares any common space with rhs
false this IRECT and rhs are completely separate
Definition at line 842 of file IGraphicsStructs.h.
References B, Empty(), L, R, and T.
bool IRECT::IsPixelAligned () const inline
Returns
true If all the values of this IRECT are within 1/1000th of being an integer
Definition at line 1155 of file IGraphicsStructs.h.
Referenced by IGraphicsAGG::DrawBitmap(), and IsPixelAligned().
bool IRECT::IsPixelAligned (float scale) const inline
Return true if, when scaled by scale, this IRECT is pixel aligned When scaling this mutliples each value of the IRECT, it does not scale from the center.
Parameters
scale Scale value for the test
Returns
true The scaled IRECT is pixel-aligned
Definition at line 1168 of file IGraphicsStructs.h.
References IsPixelAligned(), and Scale().
static IRECT IRECT::LinearInterpolateBetween (const IRECT & start, const IRECT & dest, float progress) inline static
Get a rectangle that is a linear interpolation between start and dest
Parameters
start Starting rectangle
dest Ending rectangle
progress Interpolation point
Returns
IRECT the new rectangle
Definition at line 1467 of file IGraphicsStructs.h.
References B, L, R, and T.
Referenced by IVSwitchControl::OnInit().
static IRECT IRECT::MakeXYWH (float l, float t, float w, float h) inline static
Create a new IRECT with the given position and size.
Parameters
l Left/X of new IRECT
t Top/Y of new IRECT
w Width of new IRECT
h Height of new IRECT
Returns
the new IRECT
Definition at line 773 of file IGraphicsStructs.h.
Referenced by IBSwitchControl::OnMouseDown().
bool IRECT::Mergeable (const IRECT & rhs) const inline
Return if this IRECT and rhs may be merged.
The two rects cover exactly the area returned by Union()
Parameters
rhs another IRECT
Returns
true this IRECT wholly contains rhs or rhs wholly contains this IRECT
false any part of these IRECTs does not overlap
Definition at line 901 of file IGraphicsStructs.h.
References B, Empty(), L, R, and T.
float IRECT::MH () const inline
Returns
float the midpoint of this IRECT on the y-axis (middle-height)
Definition at line 810 of file IGraphicsStructs.h.
Referenced by IPopupMenuControl::CalculateMenuPanels(), IGraphics::CalculateTextRotation(), IPattern::CreateLinearGradient(), IGraphicsLice::DoDrawText(), TestMaskControl::Draw(), TestDrawContextControl::Draw(), TestLayerControl::Draw(), TestPolyControl::Draw(), TestMultiPathControl::Draw(), TestDropShadowControl::Draw(), TestArcControl::Draw(), TestGesturesControl::Draw(), TestBezierControl::Draw(), ILEDControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::Draw(), IVLEDMeterControl< MAXNC >::Draw(), IVSliderControl::Draw(), IVRangeSliderControl::Draw(), ISVGKnobControl::Draw(), IBKnobRotaterControl::Draw(), ITextControl::Draw(), IURLControl::Draw(), PlaceHolder::Draw(), IPopupMenuControl::DrawCalloutArrow(), IGraphics::DrawRotatedLayer(), IPopupMenuControl::DrawSubMenuArrow(), IGraphicsAGG::EndFrame(), IVKnobControl::GetKnobDragBounds(), IGraphicsCairo::GetPoint(), IGraphicsLice::GetPoint(), IGraphicsNanoVG::GetPoint(), IGraphicsSkia::LoadAPIFont(), TestColorControl::OnResize(), TestGradientControl::OnResize(), ISVGSliderControl::OnResize(), IGraphicsPathBase::PathEllipse(), IGraphicsCanvas::PathFill(), IControl::PromptUserInput(), IBubbleControl::SetMaxBounds(), and ShowBubbleHorizontalActionFunc().
void IRECT::MidHPad (float padding) inline
Set the width of this IRECT to 2*padding without changing it's center point on the X-axis.
Parameters
padding Left and right padding (1/2 the new width)
Definition at line 1297 of file IGraphicsStructs.h.
void IRECT::MidVPad (float padding) inline
Set the height of this IRECT to 2*padding without changing it's center point on the Y-axis.
Parameters
padding Top and bottom padding (1/2 the new height)
Definition at line 1306 of file IGraphicsStructs.h.
float IRECT::MW () const inline
Returns
float the midpoint of this IRECT on the x-axis (middle-width)
Definition at line 807 of file IGraphicsStructs.h.
Referenced by IPopupMenuControl::CalculateMenuPanels(), IGraphics::CalculateTextRotation(), IPattern::CreateLinearGradient(), IGraphicsLice::DoDrawText(), TestMaskControl::Draw(), TestDrawContextControl::Draw(), TestLayerControl::Draw(), TestPolyControl::Draw(), TestMultiPathControl::Draw(), TestArcControl::Draw(), TestDropShadowControl::Draw(), TestGesturesControl::Draw(), TestBezierControl::Draw(), TestDirBrowseControl::Draw(), ILEDControl::Draw(), IVLEDMeterControl< MAXNC >::Draw(), IVSliderControl::Draw(), IVRangeSliderControl::Draw(), IVGroupControl::Draw(), ISVGKnobControl::Draw(), IBKnobRotaterControl::Draw(), ITextControl::Draw(), IURLControl::Draw(), ICaptionControl::Draw(), PlaceHolder::Draw(), IPopupMenuControl::DrawCalloutArrow(), IPopupMenuControl::DrawDownArrow(), IVectorBase::DrawPressableTriangle(), IGraphics::DrawRotatedLayer(), IPopupMenuControl::DrawUpArrow(), IGraphicsAGG::EndFrame(), IVKnobControl::GetKnobDragBounds(), IGraphicsCairo::GetPoint(), IGraphicsLice::GetPoint(), IGraphicsNanoVG::GetPoint(), IGraphicsSkia::LoadAPIFont(), ITextEntryControl::OnKeyDown(), TestGradientControl::OnResize(), IGraphicsPathBase::PathEllipse(), IGraphicsCanvas::PathFill(), IControl::PromptUserInput(), IBubbleControl::SetMaxBounds(), and ShowBubbleVerticalActionFunc().
void IRECT::Pad (float padding) inline
Pad this IRECT N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Padding amount
Definition at line 1255 of file IGraphicsStructs.h.
Referenced by IPopupMenuControl::CreatePopupMenu(), GFXLabelControl::Draw(), IVNumberBoxControl::OnAttached(), IVNumberBoxControl::OnResize(), and IBubbleControl::SetMaxBounds().
void IRECT::Pad (float padL, float padT, float padR, float padB) inline
Pad this IRECT N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padL Left-padding
padT Top-padding
padR Right-padding
padB Bottom-padding
Definition at line 1269 of file IGraphicsStructs.h.
void IRECT::PixelAlign (float scale) inline
Pixel-align this IRECT at the given scale factor then scale it back down When scaling this mutliples each value of the IRECT, it does not scale from the center.
Parameters
scale Scale value for the alignment
Definition at line 1187 of file IGraphicsStructs.h.
void IRECT::PixelSnap () inline
Pixel aligns to nearest pixels This may make the IRECT smaller, unlike PixelAlign().
Definition at line 1216 of file IGraphicsStructs.h.
Referenced by GetPixelSnapped().
void IRECT::PixelSnap (float scale) inline
Pixel align a scaled version of this IRECT.
Parameters
scale Scaling factor for the alignment
Definition at line 1226 of file IGraphicsStructs.h.
IRECT IRECT::ReduceFromBottom (float amount) inline
Reduce in height from the bottom edge by 'amount' and return the removed region.
Parameters
amount Size in Y to reduce by
Returns
IRECT The removed subrect
Definition at line 1067 of file IGraphicsStructs.h.
Referenced by IVectorBase::DrawPressableRectangle().
IRECT IRECT::ReduceFromLeft (float amount) inline
Reduce in width from the left edge by 'amount' and return the removed region.
Parameters
amount Size in X to reduce by
Returns
IRECT The removed subrect
Definition at line 1072 of file IGraphicsStructs.h.
Referenced by IVBakedPresetManagerControl::OnAttached(), IVNumberBoxControl::OnAttached(), IVDiskPresetManagerControl::OnAttached(), and IVNumberBoxControl::OnResize().
IRECT IRECT::ReduceFromRight (float amount) inline
Reduce in width from the right edge by 'amount' and return the removed region.
Parameters
amount Size in X to reduce by
Returns
IRECT The removed subrect
Definition at line 1077 of file IGraphicsStructs.h.
Referenced by IVectorBase::DrawPressableRectangle(), and IVDiskPresetManagerControl::OnAttached().
IRECT IRECT::ReduceFromTop (float amount) inline
Reduce in height from the top edge by 'amount' and return the removed region.
Parameters
amount Size in Y to reduce by
Returns
IRECT The removed subrect
Definition at line 1062 of file IGraphicsStructs.h.
void IRECT::Scale (float scale) inline
Multiply each field of this IRECT by scale.
Parameters
scale The amount to multiply each field by
Definition at line 1420 of file IGraphicsStructs.h.
Referenced by IGraphicsLice::DoDrawText(), IGraphicsCanvas::DrawBitmap(), IGraphicsAGG::DrawBitmap(), IGraphicsLice::GetBackingPixelScale(), GetScaled(), and IsPixelAligned().
void IRECT::ScaleAboutCentre (float scale) inline
Scale the width and height of this IRECT by scale without changing the center point.
Parameters
scale The scaling factor
Definition at line 1430 of file IGraphicsStructs.h.
References IBitmap::H(), and IBitmap::W().
Referenced by GetScaledAboutCentre().
IRECT IRECT::SubRect (EDirection layoutDir, int numSlices, int sliceIdx) const inline
Get a new rectangle which is a "slice" of this rectangle.
Parameters
layoutDir EDirection::Vertical or EDirection::Horizontal
numSlices Number of equal-sized parts to divide this IRECT into
sliceIdx Which "slice" to return
Returns
IRECT the new rectangle
Definition at line 987 of file IGraphicsStructs.h.
Referenced by IVTrackControlBase::DrawTrackHandle(), IVSwitchControl::OnInit(), and IVTabSwitchControl::OnResize().
IRECT IRECT::SubRectHorizontal (int numSlices, int sliceIdx) const inline
Returns a new IRECT which is a vertical "slice" of this IRECT.
First divide the current width into numSlices equal parts, then return the n'th "slice" where "n" is sliceIdx. The returned IRECT will have the same height as this IRECT.
Parameters
numSlices number of equal-sized parts to divide this IRECT into
sliceIdx which "slice" to select
Returns
IRECT the new IRECT
Definition at line 974 of file IGraphicsStructs.h.
References IBitmap::W().
Referenced by GetGridCell().
IRECT IRECT::SubRectVertical (int numSlices, int sliceIdx) const inline
Returns a new IRECT which is a horizontal "slice" of this IRECT.
First divide the current height into numSlices equal parts, then return the n'th "slice" where "n" is sliceIdx. The returned IRECT will have the same width as this IRECT.
Parameters
numSlices number of equal-sized parts to divide this IRECT into
sliceIdx which "slice" to select
Returns
IRECT the new IRECT
Definition at line 959 of file IGraphicsStructs.h.
References IBitmap::H().
Referenced by GetGridCell().
void IRECT::Translate (float x, float y) inline
Translate this rectangle.
Parameters
x Offset in the X axis
y Offset in the Y axis
Definition at line 1527 of file IGraphicsStructs.h.
Referenced by IGraphicsLice::DoDrawText(), IGraphics::DoMeasureTextRotation(), IBSliderControl::Draw(), IGraphicsAGG::DrawBitmap(), IGraphicsLice::GetBackingPixelScale(), IVGroupControl::OnResize(), and IBubbleControl::SetMaxBounds().
IRECT IRECT::Union (const IRECT & rhs) const inline
Create a new IRECT that is a union of this IRECT and rhs.
The resulting IRECT will have the minimim L and T values and maximum R and B values of the inputs.
Parameters
rhs another IRECT
Returns
IRECT the new IRECT
Definition at line 819 of file IGraphicsStructs.h.
References B, Empty(), L, R, and T.
Referenced by IRECTList::Bounds(), IPopupMenuControl::CalculateMenuPanels(), IGraphics::CalculateTextRotation(), IPopupMenuControl::CreatePopupMenu(), GetGridCell(), IVGroupControl::OnResize(), and IBubbleControl::SetMaxBounds().
void IRECT::VAlignTo (const IRECT & sr, EVAlign align) inline
Vertically align this rect to the reference IRECT.
Parameters
sr the source IRECT to use as reference
align the vertical alignment
Definition at line 1611 of file IGraphicsStructs.h.
References B, IBitmap::H(), H(), and T.
Referenced by GetVAlignedTo().
void IRECT::VPad (float padding) inline
Pad this IRECT in the Y-axis N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Top and bottom padding
Definition at line 1289 of file IGraphicsStructs.h.
float IRECT::W () const inline
Returns
float the width of this IRECT
Definition at line 801 of file IGraphicsStructs.h.
Referenced by IGraphics::BeginFrame(), IPopupMenuControl::CalculateMenuPanels(), IPopupMenuControl::CreatePopupMenu(), IGraphicsCanvas::DoDrawText(), IGraphicsLice::DoDrawText(), IGraphicsCanvas::DoMeasureText(), IGraphicsCairo::DoMeasureText(), IGraphicsLice::DoMeasureText(), IGraphicsSkia::DoMeasureText(), IGraphicsNanoVG::DoMeasureText(), IGraphicsAGG::DoMeasureText(), TestMaskControl::Draw(), TestDrawContextControl::Draw(), TestLayerControl::Draw(), TestPolyControl::Draw(), TestShadowGradientControl::Draw(), TestMultiPathControl::Draw(), TestArcControl::Draw(), TestDropShadowControl::Draw(), TestFontControl::Draw(), IColorPickerControl::Draw(), ILEDControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::Draw(), ISkLottieControl::Draw(), IVDisplayControl::Draw(), IFPSDisplayControl::Draw(), IVLEDMeterControl< MAXNC >::Draw(), IVKeyboardControl::Draw(), ISkShaderControl::Draw(), IVXYPadControl::Draw(), IVPlotControl::Draw(), ISVGKnobControl::Draw(), IWheelControl::Draw(), ITextControl::Draw(), IURLControl::Draw(), ICaptionControl::Draw(), IGraphicsCanvas::DrawBitmap(), IGraphicsLice::DrawBitmap(), IGraphicsCairo::DrawBitmap(), IGraphicsNanoVG::DrawBitmap(), IGraphics::DrawBitmapedText(), IGraphicsPathBase::DrawData(), IGraphicsNanoVG::DrawDottedRect(), IGraphicsLice::DrawFittedBitmap(), IGraphicsPathBase::DrawFittedBitmap(), IGraphics::DrawFittedLayer(), IGraphics::DrawGrid(), IPopupMenuControl::DrawPanelShadow(), IVectorBase::DrawPressableTriangle(), IGraphicsLice::DrawRoundRect(), IGraphicsPathBase::DrawSVG(), IGraphicsLice::FillRect(), IGraphicsLice::FillRoundRect(), GetCentredInside(), IRECTList::GetFracGrid(), IVKnobControl::GetKnobDragBounds(), HAlignTo(), IFlexBox::Init(), IVRadioButtonControl::IVRadioButtonControl(), IGraphicsCairo::LoadAPIFont(), IGraphicsNanoVG::LoadAPIFont(), IWebViewControl::OnAttached(), IVNumberBoxControl::OnAttached(), ICornerResizerControl::OnMouseDblClick(), IShaderControl::OnMouseDown(), IShaderControl::OnMouseDrag(), IGraphicsLiveEdit::OnMouseDrag(), IVXYPadControl::OnMouseDrag(), IShaderControl::OnMouseUp(), IWebViewControl::OnRescale(), TestDirBrowseControl::OnResize(), TestSizeControl::OnResize(), TestGradientControl::OnResize(), IVNumberBoxControl::OnResize(), IWebViewControl::OnResize(), IShaderControl::OnResize(), IVKeyboardControl::OnResize(), ISVGSliderControl::OnResize(), PlaceHolder::OnResize(), IGraphicsPathBase::PathEllipse(), IGraphicsPathBase::PathRoundRect(), IBubbleControl::SetMaxBounds(), IVTrackControlBase::SetParams(), IControl::SetPosition(), IVMultiSliderControl< MAXNC >::SnapToMouse(), IControl::SnapToMouse(), IGraphics::StartLayer(), and IMatrix::Transform().
The documentation for this struct was generated from the following file:
IGraphicsStructs.h